CREATE DATABASE [FIL_MyBase]
CONTAINMENT = NONE
ON PRIMARY
(NAME = N'FIL_MyBase',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SARVAR\MSSQL\DATA\FIL_MyBase.mdf',
SIZE = 5120KB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB
)
LOG ON(
NAME = N'FIL_MyBase_log',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SARVAR\MSSQL\DATA\FIL_MyBase_log.ldf',
SIZE = 1024KB, MAXSIZE = 2048GB, FILEGROWTH = 10%
)
GO