use UNIVER;

select AUDITORIUM_NAME as Name, AUDITORIUM_CAPACITY as Capacity,AUDITORIUM_TYPE as Type from AUDITORIUM a where AUDITORIUM_CAPACITY = 
(select top(1)AUDITORIUM_CAPACITY from AUDITORIUM aa where aa.AUDITORIUM_TYPE  =a.AUDITORIUM_TYPE) order by AUDITORIUM_CAPACITY