use UNIVER;
select AUDITORIUM.AUDITORIUM_NAME,AUDITORIUM.AUDITORIUM_TYPE,AUDITORIUM.AUDITORIUM_CAPACITY from AUDITORIUM where AUDITORIUM_TYPE like '%À %'
select AUDITORIUM.AUDITORIUM_NAME as Name, AUDITORIUM.AUDITORIUM_CAPACITY as Capacity from AUDITORIUM where AUDITORIUM.AUDITORIUM_CAPACITY>=all(select AUDITORIUM_CAPACITY from AUDITORIUM where AUDITORIUM_TYPE like '%À %')