use UNIVER;




select PROGRESS.IDSTUDENT as Id , PROGRESS.NOTE as Note, PROGRESS.SUBJECT as Subject from PROGRESS where PROGRESS.NOTE>any(select PROGRESS.NOTE from PROGRESS ) and PROGRESS.SUBJECT like 'Œ¿Ëœ'